<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Upload\Module'                        => __DIR__ . '/Module.php',
    'Upload\Controller\UploadController' => __DIR__ . '/src/Upload/Controller/UploadController.php',
    'UploadTest\Framework\TestCase'        => __DIR__ . '/tests/Upload/Framework/TestCase.php',
    'UploadTest\SampleTest'                => __DIR__ . '/tests/Upload/SampleTest.php',
);
