
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <script src="<?php echo $this->basepath().'/public/js/dropme.js';?>"></script>
	<link type="text/css" href="<?php echo $this->basepath().'/public/css/dropme.css';?>" rel="stylesheet" media="screen">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->

             	<link type="text/css" href="<?php echo $this->basepath();?>/public/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
             	<link type="text/css" href="<?php echo $this->basepath();?>/public/css/style.css" rel="stylesheet" media="screen">
             	<link type="text/css" href="<?php echo $this->basepath();?>/public/css/bootstrap.min.css" rel="stylesheet" media="screen">
                        
                        

        <!-- Scripts -->
            <script src="<?php echo $this->basepath().'/public/js/html5.js';?>"></script>
            <script src="<?php echo $this->basepath().'/public/js/bootstrap.min.js';?>"></script>
            <script src="<?php echo $this->basepath().'/public/js/jquery.min.js';?>"></script>
        
        

    
    
    </head>
    <body>
    

            <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">GoodFeat</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                        <?php if (!$this->identity): ?>
                            <li class="active"><a href="#">Home</a></li>
                          <li class="active"><a href="<?php echo $this->url('users', array('action' => 'login')); ?>">Login</a></li>
                          
                           <?php else:?>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'index')).'?user='.$identity;?>">Upload</a></li>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'download')).'?user='.$identity;?>">Download</a></li>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'Manage')).'?user='.$identity;?>">Manage</a></li>               
                            <li class="active"><a href="<?php echo $this->url('users', array('action' => 'logout')); ?>">Logout</a></li>
                        <?php endif;?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
<?php echo $this->content;?>

<hr>
<footer>
    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
        
    </body>
</html>
