
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <script src="<?php echo $this->basepath().'/js/dropme.js';?>"></script>
	<link type="text/css" href="<?php echo $this->basePath();?>/css/dropme.css" rel="stylesheet" media="screen">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
            <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">GoodFeat</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                        <?php if (!$this->identity): ?>
                            <li class="active"><a href="#">Home</a></li>
                          <li class="active"><a href="<?php echo $this->url('users', array('action' => 'login')); ?>">Login</a></li>
                          
                           <?php else:?>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'index')).'?user='.$identity;?>">Upload</a></li>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'download')).'?user='.$identity;?>">Download</a></li>
                            <li class="active"><a href="<?php echo $this->url('Upload', array('action' => 'Manage')).'?user='.$identity;?>">Manage</a></li>               
                            <li class="active"><a href="<?php echo $this->url('users', array('action' => 'logout')); ?>">Logout</a></li>
                        <?php endif;?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
<?php echo $this->content;?>
        
    </body>
</html>
