<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>uploader</title>
	<style>
	body {
		font-family: Verdana;
		text-align:center;
	}
	#box {
		background-color: red;
		width: 500px;
		border: 1px solid #f60;
		-webkit-border-radius: 6px;
		-moz-border-radius: 6px;
		border-radius: 6px;
		padding-bottom: 10px;
		float: left;
		text-align:center;
	}
	#box p {
		font-size: 10px;
		padding: 5px;
		margin: 0px;
	}
	#drop {
		width: 500px;
		height: 200px;
		background-color: green;
	}
	#status {
		width: 500px;
		height: 25px;
		font-size: 10px;
		color: #fff;
		padding: 5px;
	}
	#list {
		width: 500px;
		font-size: 10px;
		float: left;
		margin-left: 10px;
	}
	.addedIMG {
		width: 100px;
		height: 100px;
	}
	</style>
	<script src="<?php echo $this->basepath().'/js/upload.js';?>"></script>
</head>

<body onload="new uploader('drop', 'status', '<?php echo $this->url('Upload',array('action'=>'uploaded'));?>', 'list','<?php echo $this->user;?>');">
	
		
	
	<div id="box">
		<div id="status">Drag the images from a folder to a selected area ...</div>
		<div id="drop"></div>
		<p>Files are not stored on the server Weeby, you see only a preview.</p>
	</div>
	<div id="list"></div>
</body>
</html>